/**
 * Definitions for the `@wordpress/icons` package.
 *
 * Currently not available as a global variable and must
 * be used from the package directly.
 *
 * It's possible to use an icon constant directly, but it will
 * always be 24 by 24. To support changing size or other SVG
 * attributes use it like so.
 * `<Icon icon={ check } size={48} />`
 *
 * @link https://developer.wordpress.org/block-editor/reference-guides/packages/packages-icons/
 *
 * @note You must install the `@wordpress/icons` package to use these icons as
 *       they are not included in WP core. The package has its own Types, but they
 *       are cumbersome to search, hence why these definitions exist.
 *
 */
declare module '@wordpress/icons' {
	import {ComponentType} from '@lipemat/js-boilerplate/helpers';
	import {SVGAttributes} from 'react';

	type IconType = JSX.Element;

	interface Icon extends SVGAttributes<SVGElement> {
		icon: IconType;
		size?: number;
	}

	export const Icon: ComponentType<Icon>;

	export const addCard: IconType;
	export const addSubmenu: IconType;
	export const addTemplate: IconType;
	export const alignCenter: IconType;
	export const alignJustify: IconType;
	export const alignLeft: IconType;
	export const alignNone: IconType;
	export const alignRight: IconType;
	export const archive: IconType;
	export const arrowDown: IconType;
	export const arrowLeft: IconType;
	export const arrowRight: IconType;
	export const arrowUp: IconType;
	export const aspectRatio: IconType;
	export const atSymbol: IconType;
	export const audio: IconType;
	export const backup: IconType;
	export const blockDefault: IconType;
	export const blockMeta: IconType;
	export const blockTable: IconType;
	export const border: IconType;
	export const box: IconType;
	export const brush: IconType;
	export const bug: IconType;
	export const button: IconType;
	export const buttons: IconType;
	export const calendar: IconType;
	export const cancelCircleFilled: IconType;
	export const caption: IconType;
	export const capturePhoto: IconType;
	export const captureVideo: IconType;
	export const category: IconType;
	export const chartBar: IconType;
	export const check: IconType;
	export const chevronDown: IconType;
	export const chevronLeft: IconType;
	export const chevronLeftSmall: IconType;
	export const chevronRight: IconType;
	export const chevronRightSmall: IconType;
	export const chevronUp: IconType;
	export const chevronUpDown: IconType;
	export const classic: IconType;
	export const close: IconType;
	export const closeSmall: IconType;
	export const cloud: IconType;
	export const cloudUpload: IconType;
	export const code: IconType;
	export const cog: IconType;
	export const color: IconType;
	export const column: IconType;
	export const columns: IconType;
	export const comment: IconType;
	export const commentAuthorAvatar: IconType;
	export const commentAuthorName: IconType;
	export const commentContent: IconType;
	export const commentEditLink: IconType;
	export const commentReplyLink: IconType;
	export const copy: IconType;
	export const cover: IconType;
	export const create: IconType;
	export const crop: IconType;
	export const currencyDollar: IconType;
	export const currencyEuro: IconType;
	export const currencyPound: IconType;
	export const customLink: IconType;
	export const customPostType: IconType;
	export const desktop: IconType;
	export const details: IconType;
	export const download: IconType;
	export const dragHandle: IconType;
	export const drawerLeft: IconType;
	export const drawerRight: IconType;
	export const edit: IconType;
	export const external: IconType;
	export const file: IconType;
	export const filter: IconType;
	export const flipHorizontal: IconType;
	export const flipVertical: IconType;
	export const footer: IconType;
	export const formatBold: IconType;
	export const formatCapitalize: IconType;
	export const formatIndent: IconType;
	export const formatIndentRTL: IconType;
	export const formatItalic: IconType;
	export const formatListBullets: IconType;
	export const formatListBulletsRTL: IconType;
	export const formatListNumbered: IconType;
	export const formatListNumberedRTL: IconType;
	export const formatLowercase: IconType;
	export const formatLtr: IconType;
	export const formatOutdent: IconType;
	export const formatOutdentRTL: IconType;
	export const formatRtl: IconType;
	export const formatStrikethrough: IconType;
	export const formatUnderline: IconType;
	export const formatUppercase: IconType;
	export const fullscreen: IconType;
	export const gallery: IconType;
	export const globe: IconType;
	export const grid: IconType;
	export const group: IconType;
	export const handle: IconType;
	export const header: IconType;
	export const heading: IconType;
	export const help: IconType;
	export const helpFilled: IconType;
	export const home: IconType;
	export const html: IconType;
	export const image: IconType;
	export const inbox: IconType;
	export const info: IconType;
	export const insertAfter: IconType;
	export const insertBefore: IconType;
	export const institution: IconType;
	export const justifyCenter: IconType;
	export const justifyLeft: IconType;
	export const justifyRight: IconType;
	export const justifySpaceBetween: IconType;
	export const justifyStretch: IconType;
	export const key: IconType;
	export const keyboardClose: IconType;
	export const keyboardReturn: IconType;
	export const layout: IconType;
	export const lifesaver: IconType;
	export const lineDashed: IconType;
	export const lineDotted: IconType;
	export const lineSolid: IconType;
	export const link: IconType;
	export const linkOff: IconType;
	export const list: IconType;
	export const listItem: IconType;
	export const listView: IconType;
	export const lock: IconType;
	export const lockOutline: IconType;
	export const lockSmall: IconType;
	export const login: IconType;
	export const loop: IconType;
	export const mapMarker: IconType;
	export const media: IconType;
	export const mediaAndText: IconType;
	export const megaphone: IconType;
	export const menu: IconType;
	export const mobile: IconType;
	export const more: IconType;
	export const moreHorizontal: IconType;
	export const moreHorizontalMobile: IconType;
	export const moreVertical: IconType;
	export const moveTo: IconType;
	export const navigation: IconType;
	export const next: IconType;
	export const notFound: IconType;
	export const overlayText: IconType;
	export const page: IconType;
	export const pageBreak: IconType;
	export const pages: IconType;
	export const paragraph: IconType;
	export const payment: IconType;
	export const pencil: IconType;
	export const people: IconType;
	export const percent: IconType;
	export const pin: IconType;
	export const plugins: IconType;
	export const plus: IconType;
	export const plusCircle: IconType;
	export const plusCircleFilled: IconType;
	export const positionCenter: IconType;
	export const positionLeft: IconType;
	export const positionRight: IconType;
	export const post: IconType;
	export const postAuthor: IconType;
	export const postCategories: IconType;
	export const postComments: IconType;
	export const postCommentsCount: IconType;
	export const postCommentsForm: IconType;
	export const postContent: IconType;
	export const postDate: IconType;
	export const postExcerpt: IconType;
	export const postFeaturedImage: IconType;
	export const postList: IconType;
	export const postTerms: IconType;
	export const preformatted: IconType;
	export const previous: IconType;
	export const pullLeft: IconType;
	export const pullRight: IconType;
	export const pullquote: IconType;
	export const queryPagination: IconType;
	export const queryPaginationNext: IconType;
	export const queryPaginationNumbers: IconType;
	export const queryPaginationPrevious: IconType;
	export const quote: IconType;
	export const receipt: IconType;
	export const redo: IconType;
	export const removeBug: IconType;
	export const removeSubmenu: IconType;
	export const replace: IconType;
	export const reset: IconType;
	export const resizeCornerNE: IconType;
	export const reusableBlock: IconType;
	export const rotateLeft: IconType;
	export const rotateRight: IconType;
	export const row: IconType;
	export const rss: IconType;
	export const search: IconType;
	export const seen: IconType;
	export const separator: IconType;
	export const settings: IconType;
	export const shadow: IconType;
	export const share: IconType;
	export const shield: IconType;
	export const shipping: IconType;
	export const shortcode: IconType;
	export const shuffle: IconType;
	export const sidebar: IconType;
	export const siteLogo: IconType;
	export const stack: IconType;
	export const starEmpty: IconType;
	export const starFilled: IconType;
	export const starHalf: IconType;
	export const store: IconType;
	export const stretchFullWidth: IconType;
	export const stretchWide: IconType;
	export const styles: IconType;
	export const subscript: IconType;
	export const superscript: IconType;
	export const swatch: IconType;
	export const symbol: IconType;
	export const symbolFilled: IconType;
	export const table: IconType;
	export const tableColumnAfter: IconType;
	export const tableColumnBefore: IconType;
	export const tableColumnDelete: IconType;
	export const tableRowAfter: IconType;
	export const tableRowBefore: IconType;
	export const tableRowDelete: IconType;
	export const tablet: IconType;
	export const tag: IconType;
	export const termDescription: IconType;
	export const textColor: IconType;
	export const tip: IconType;
	export const title: IconType;
	export const tool: IconType;
	export const trash: IconType;
	export const trendingDown: IconType;
	export const trendingUp: IconType;
	export const typography: IconType;
	export const undo: IconType;
	export const ungroup: IconType;
	export const unlock: IconType;
	export const unseen: IconType;
	export const update: IconType;
	export const upload: IconType;
	export const verse: IconType;
	export const video: IconType;
	export const warning: IconType;
	export const widget: IconType;
	export const wordpress: IconType;

	export default interface Icons {
		Icon: ComponentType<Icon>;

		addCard: IconType;
		addSubmenu: IconType;
		addTemplate: IconType;
		alignCenter: IconType;
		alignJustify: IconType;
		alignLeft: IconType;
		alignNone: IconType;
		alignRight: IconType;
		archive: IconType;
		arrowDown: IconType;
		arrowLeft: IconType;
		arrowRight: IconType;
		arrowUp: IconType;
		aspectRatio: IconType;
		atSymbol: IconType;
		audio: IconType;
		backup: IconType;
		blockDefault: IconType;
		blockMeta: IconType;
		blockTable: IconType;
		border: IconType;
		box: IconType;
		brush: IconType;
		bug: IconType;
		button: IconType;
		buttons: IconType;
		calendar: IconType;
		cancelCircleFilled: IconType;
		caption: IconType;
		capturePhoto: IconType;
		captureVideo: IconType;
		category: IconType;
		chartBar: IconType;
		check: IconType;
		chevronDown: IconType;
		chevronLeft: IconType;
		chevronLeftSmall: IconType;
		chevronRight: IconType;
		chevronRightSmall: IconType;
		chevronUp: IconType;
		chevronUpDown: IconType;
		classic: IconType;
		close: IconType;
		closeSmall: IconType;
		cloud: IconType;
		cloudUpload: IconType;
		code: IconType;
		cog: IconType;
		color: IconType;
		column: IconType;
		columns: IconType;
		comment: IconType;
		commentAuthorAvatar: IconType;
		commentAuthorName: IconType;
		commentContent: IconType;
		commentEditLink: IconType;
		commentReplyLink: IconType;
		copy: IconType;
		cover: IconType;
		create: IconType;
		crop: IconType;
		currencyDollar: IconType;
		currencyEuro: IconType;
		currencyPound: IconType;
		customLink: IconType;
		customPostType: IconType;
		desktop: IconType;
		details: IconType;
		download: IconType;
		dragHandle: IconType;
		drawerLeft: IconType;
		drawerRight: IconType;
		edit: IconType;
		external: IconType;
		file: IconType;
		filter: IconType;
		flipHorizontal: IconType;
		flipVertical: IconType;
		footer: IconType;
		formatBold: IconType;
		formatCapitalize: IconType;
		formatIndent: IconType;
		formatIndentRTL: IconType;
		formatItalic: IconType;
		formatListBullets: IconType;
		formatListBulletsRTL: IconType;
		formatListNumbered: IconType;
		formatListNumberedRTL: IconType;
		formatLowercase: IconType;
		formatLtr: IconType;
		formatOutdent: IconType;
		formatOutdentRTL: IconType;
		formatRtl: IconType;
		formatStrikethrough: IconType;
		formatUnderline: IconType;
		formatUppercase: IconType;
		fullscreen: IconType;
		gallery: IconType;
		globe: IconType;
		grid: IconType;
		group: IconType;
		handle: IconType;
		header: IconType;
		heading: IconType;
		help: IconType;
		helpFilled: IconType;
		home: IconType;
		html: IconType;
		image: IconType;
		inbox: IconType;
		info: IconType;
		insertAfter: IconType;
		insertBefore: IconType;
		institution: IconType;
		justifyCenter: IconType;
		justifyLeft: IconType;
		justifyRight: IconType;
		justifySpaceBetween: IconType;
		justifyStretch: IconType;
		key: IconType;
		keyboardClose: IconType;
		keyboardReturn: IconType;
		layout: IconType;
		lifesaver: IconType;
		lineDashed: IconType;
		lineDotted: IconType;
		lineSolid: IconType;
		link: IconType;
		linkOff: IconType;
		list: IconType;
		listItem: IconType;
		listView: IconType;
		lock: IconType;
		lockOutline: IconType;
		lockSmall: IconType;
		login: IconType;
		loop: IconType;
		mapMarker: IconType;
		media: IconType;
		mediaAndText: IconType;
		megaphone: IconType;
		menu: IconType;
		mobile: IconType;
		more: IconType;
		moreHorizontal: IconType;
		moreHorizontalMobile: IconType;
		moreVertical: IconType;
		moveTo: IconType;
		navigation: IconType;
		next: IconType;
		notFound: IconType;
		overlayText: IconType;
		page: IconType;
		pageBreak: IconType;
		pages: IconType;
		paragraph: IconType;
		payment: IconType;
		pencil: IconType;
		people: IconType;
		percent: IconType;
		pin: IconType;
		plugins: IconType;
		plus: IconType;
		plusCircle: IconType;
		plusCircleFilled: IconType;
		positionCenter: IconType;
		positionLeft: IconType;
		positionRight: IconType;
		post: IconType;
		postAuthor: IconType;
		postCategories: IconType;
		postComments: IconType;
		postCommentsCount: IconType;
		postCommentsForm: IconType;
		postContent: IconType;
		postDate: IconType;
		postExcerpt: IconType;
		postFeaturedImage: IconType;
		postList: IconType;
		postTerms: IconType;
		preformatted: IconType;
		previous: IconType;
		pullLeft: IconType;
		pullRight: IconType;
		pullquote: IconType;
		queryPagination: IconType;
		queryPaginationNext: IconType;
		queryPaginationNumbers: IconType;
		queryPaginationPrevious: IconType;
		quote: IconType;
		receipt: IconType;
		redo: IconType;
		removeBug: IconType;
		removeSubmenu: IconType;
		replace: IconType;
		reset: IconType;
		resizeCornerNE: IconType;
		reusableBlock: IconType;
		rotateLeft: IconType;
		rotateRight: IconType;
		row: IconType;
		rss: IconType;
		search: IconType;
		seen: IconType;
		separator: IconType;
		settings: IconType;
		shadow: IconType;
		share: IconType;
		shield: IconType;
		shipping: IconType;
		shortcode: IconType;
		shuffle: IconType;
		sidebar: IconType;
		siteLogo: IconType;
		stack: IconType;
		starEmpty: IconType;
		starFilled: IconType;
		starHalf: IconType;
		store: IconType;
		stretchFullWidth: IconType;
		stretchWide: IconType;
		styles: IconType;
		subscript: IconType;
		superscript: IconType;
		swatch: IconType;
		symbol: IconType;
		symbolFilled: IconType;
		table: IconType;
		tableColumnAfter: IconType;
		tableColumnBefore: IconType;
		tableColumnDelete: IconType;
		tableRowAfter: IconType;
		tableRowBefore: IconType;
		tableRowDelete: IconType;
		tablet: IconType;
		tag: IconType;
		termDescription: IconType;
		textColor: IconType;
		tip: IconType;
		title: IconType;
		tool: IconType;
		trash: IconType;
		trendingDown: IconType;
		trendingUp: IconType;
		typography: IconType;
		undo: IconType;
		ungroup: IconType;
		unlock: IconType;
		unseen: IconType;
		update: IconType;
		upload: IconType;
		verse: IconType;
		video: IconType;
		warning: IconType;
		widget: IconType;
		wordpress: IconType;
	}
}
